Repository svaarala/duktape, pull requests merged in 2019-09, with the labels that each got.

#2172 Add DUK_WO_UNREACHABLE()
  RELEASES.rst
  config/header-snippets/compiler_fillins.h.in
  src-input/duk_js_ops.c
Labels: portability

#2174 Add RISC-V architecture detection
  RELEASES.rst
  config/architectures.yaml
  config/architectures/architecture_riscv32.h.in
  config/architectures/architecture_riscv64.h.in
  config/helper-snippets/DUK_F_RISCV.h.in
Labels: portability

#2175 Fixes for behavior of proxied arrays
  RELEASES.rst
  src-input/duk_api_internal.h
  src-input/duk_api_stack.c
  src-input/duk_bi_array.c
  src-input/duk_bi_json.c
  src-input/duk_bi_object.c
  tests/api/test-is-array-proxy.c
  tests/ecmascript/test-bi-object-proto-tostring.js
  tests/ecmascript/test-bi-proxy-isarray.js
  website/api/duk_is_array.yaml
Labels: compliance

#2176 More fixes for proxied Array handling
  RELEASES.rst
  src-input/duk_api_internal.h
  src-input/duk_api_stack.c
  src-input/duk_bi_array.c
  src-input/duk_bi_json.c
  src-input/duk_bi_object.c
  src-input/duk_hobject_class.c
  src-input/duk_js.h
  src-input/duk_js_ops.c
  src-input/strings.yaml
  tests/ecmascript/test-bi-array-proto-concat-isconcatspreadable.js
  tests/ecmascript/test-bi-cbor-enc-types.js
  tests/ecmascript/test-bi-json-enc-replacer-proxy.js
Labels: compliance

#2177 Add minimum size check for abandoning array
  RELEASES.rst
  config/config-options/DUK_USE_HOBJECT_ARRAY_ABANDON_LIMIT.yaml
  config/config-options/DUK_USE_HOBJECT_ARRAY_ABANDON_MINSIZE.yaml
  config/examples/low_memory.yaml
  src-input/duk_hobject_props.c
  tests/ecmascript/test-misc-array-fast-write.js
Labels: performance

#1514 Change header used for byteorder detection for modern Solaris
  AUTHORS.rst
  config/platforms/platform_solaris.h.in
Labels: portability

#2182 Fix some API documentation lstring examples
  website/api/duk_del_prop_lstring.yaml
  website/api/duk_get_global_lstring.yaml
  website/api/duk_put_global_lstring.yaml
Labels: documentation

#2187 Add some missing duk_def_prop() convenience constants ("EC" variants)
  RELEASES.rst
  src-input/duktape.h.in
  website/api/duk_def_prop.yaml
Labels: api
