Repository svaarala/duktape, pull requests merged in 2020-02, with the labels that each got.

#2224 Clarify third party license meaning
  dist-files/README.rst
Labels: documentation

#2229 Replace "Fork me on GitHub" for GitHub Corner
  AUTHORS.rst
  website/style-middle.css
  website/template.html
Labels: documentation

#2231 Fix navbar spacing after github corner change
  website/style-middle.css
Labels: documentation

#2235 Allow U+2028, U+2029 in string literals (ES2019)
  RELEASES.rst
  src-input/duk_lexer.c
  tests/ecmascript/test-lex-es2019-u2028-u2029-literal.js
Labels: compliance, es2019

#2236 Fix U+180E whitespace handling
  RELEASES.rst
  src-input/duk_unicode_support.c
  tests/ecmascript/test-bi-global-parsefloat.js
  tests/ecmascript/test-bi-string-trim-180e.js
Labels: compliance, es2016, unicode
