Repository svaarala/duktape, pull requests merged in 2020-03, with the labels that each got.

#2240 Enable C++ support for socket debug transport
  examples/debug-trans-socket/duk_trans_socket.h
Labels: portability

#2244 Use wasm for dukweb.js
  .gitignore
  Makefile
  RELEASES.rst
  dukweb/dukweb.html
  dukweb/dukweb_extra.js
  website/buildsite.py
Labels: webasm

#2253 README v2-maintenance branch note
  README.md
Labels: documentation

#2248 Add vcpkg installation instructions
  AUTHORS.rst
  README.md
Labels: documentation
